"""add_multitenancy_support

Revision ID: 83f98e8ef1fe
Revises: 267fb030adee
Create Date: 2026-02-01 14:00:37.747268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f98e8ef1fe'
down_revision: Union[str, Sequence[str], None] = '267fb030adee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_type', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'name', name='uq_tenant_app_name')
    )
    op.create_index(op.f('ix_tenants_application_id'), 'tenants', ['application_id'], unique=False)
    op.create_table('identity_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_idp_tenant_name')
    )
    op.create_index(op.f('ix_identity_providers_tenant_id'), 'identity_providers', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_privileged', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_role_tenant_name')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('application_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'identity_id', name='uq_app_admin_identity')
    )
    op.create_index(op.f('ix_application_admins_application_id'), 'application_admins', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_admins_identity_id'), 'application_admins', ['identity_id'], unique=False)
    op.create_table('identity_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'role_id', name='uq_identity_role')
    )
    op.create_index(op.f('ix_identity_roles_identity_id'), 'identity_roles', ['identity_id'], unique=False)
    op.create_index(op.f('ix_identity_roles_role_id'), 'identity_roles', ['role_id'], unique=False)
    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', name='uq_platform_admin_identity')
    )
    op.create_index(op.f('ix_platform_admins_identity_id'), 'platform_admins', ['identity_id'], unique=False)
    op.create_table('role_entitlements',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('entitlement_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'entitlement_id')
    )
    op.create_table('tenant_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identity_id', name='uq_tenant_admin_identity')
    )
    op.create_index(op.f('ix_tenant_admins_identity_id'), 'tenant_admins', ['identity_id'], unique=False)
    op.create_index(op.f('ix_tenant_admins_tenant_id'), 'tenant_admins', ['tenant_id'], unique=False)
    op.add_column('access_requests', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('access_requests', sa.Column('requester_identity_id', sa.UUID(), nullable=False))
    op.add_column('access_requests', sa.Column('target_identity_id', sa.UUID(), nullable=False))
    op.add_column('access_requests', sa.Column('role_id', sa.UUID(), nullable=False))
    op.add_column('access_requests', sa.Column('justification', sa.Text(), nullable=True))
    op.add_column('access_requests', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('access_requests', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('access_requests', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('access_requests', sa.Column('requested_valid_from', sa.DateTime(), nullable=True))
    op.add_column('access_requests', sa.Column('requested_valid_until', sa.DateTime(), nullable=True))
    op.add_column('access_requests', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index(op.f('ix_access_requests_identity_id'), table_name='access_requests')
    op.create_index(op.f('ix_access_requests_requester_identity_id'), 'access_requests', ['requester_identity_id'], unique=False)
    op.create_index(op.f('ix_access_requests_role_id'), 'access_requests', ['role_id'], unique=False)
    op.create_index(op.f('ix_access_requests_target_identity_id'), 'access_requests', ['target_identity_id'], unique=False)
    op.create_index(op.f('ix_access_requests_tenant_id'), 'access_requests', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('access_requests_identity_id_fkey'), 'access_requests', type_='foreignkey')
    op.create_foreign_key(None, 'access_requests', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'access_requests', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'access_requests', 'identities', ['target_identity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'access_requests', 'identities', ['requester_identity_id'], ['id'], ondelete='CASCADE')
    op.drop_column('access_requests', 'identity_id')
    op.drop_column('access_requests', 'resource')
    op.drop_column('access_requests', 'role')
    op.add_column('applications', sa.Column('deployment_type', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'applications', ['name'])
    op.add_column('audit_events', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('audit_events', sa.Column('actor_identity_id', sa.UUID(), nullable=True))
    op.add_column('audit_events', sa.Column('target_type', sa.String(length=100), nullable=True))
    op.add_column('audit_events', sa.Column('target_id', sa.UUID(), nullable=True))
    op.add_column('audit_events', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('audit_events', 'target',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_audit_events_actor_identity_id'), 'audit_events', ['actor_identity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'audit_events', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_events', 'identities', ['actor_identity_id'], ['id'], ondelete='SET NULL')
    op.add_column('entitlements', sa.Column('display_name', sa.String(length=150), nullable=True))
    op.add_column('entitlements', sa.Column('resource_type', sa.String(length=100), nullable=True))
    op.add_column('entitlements', sa.Column('action', sa.String(length=50), nullable=True))
    op.add_column('entitlements', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_entitlements_application_id'), 'entitlements', ['application_id'], unique=False)
    op.create_unique_constraint('uq_entitlement_app_name', 'entitlements', ['application_id', 'name'])
    op.drop_constraint(op.f('entitlements_application_id_fkey'), 'entitlements', type_='foreignkey')
    op.create_foreign_key(None, 'entitlements', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.add_column('identities', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('identities', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('identities', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('identities', sa.Column('identity_type', sa.String(length=50), nullable=False))
    op.add_column('identities', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('identities', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('identities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('identities', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_identities_email'), 'identities', ['email'], unique=False)
    op.create_index(op.f('ix_identities_tenant_id'), 'identities', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_identity_tenant_email', 'identities', ['tenant_id', 'email'])
    op.create_unique_constraint('uq_identity_tenant_external_id', 'identities', ['tenant_id', 'external_id'])
    op.create_foreign_key(None, 'identities', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('identities', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'identities', type_='foreignkey')
    op.drop_constraint('uq_identity_tenant_external_id', 'identities', type_='unique')
    op.drop_constraint('uq_identity_tenant_email', 'identities', type_='unique')
    op.drop_index(op.f('ix_identities_tenant_id'), table_name='identities')
    op.drop_index(op.f('ix_identities_email'), table_name='identities')
    op.drop_column('identities', 'last_login_at')
    op.drop_column('identities', 'updated_at')
    op.drop_column('identities', 'attributes')
    op.drop_column('identities', 'status')
    op.drop_column('identities', 'identity_type')
    op.drop_column('identities', 'external_id')
    op.drop_column('identities', 'email')
    op.drop_column('identities', 'tenant_id')
    op.drop_constraint(None, 'entitlements', type_='foreignkey')
    op.create_foreign_key(op.f('entitlements_application_id_fkey'), 'entitlements', 'applications', ['application_id'], ['id'])
    op.drop_constraint('uq_entitlement_app_name', 'entitlements', type_='unique')
    op.drop_index(op.f('ix_entitlements_application_id'), table_name='entitlements')
    op.drop_column('entitlements', 'extra_data')
    op.drop_column('entitlements', 'action')
    op.drop_column('entitlements', 'resource_type')
    op.drop_column('entitlements', 'display_name')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_identity_id'), table_name='audit_events')
    op.alter_column('audit_events', 'target',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('audit_events', 'details')
    op.drop_column('audit_events', 'target_id')
    op.drop_column('audit_events', 'target_type')
    op.drop_column('audit_events', 'actor_identity_id')
    op.drop_column('audit_events', 'tenant_id')
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_column('applications', 'deployment_type')
    op.add_column('access_requests', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('access_requests', sa.Column('resource', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('access_requests', sa.Column('identity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.create_foreign_key(op.f('access_requests_identity_id_fkey'), 'access_requests', 'identities', ['identity_id'], ['id'])
    op.drop_index(op.f('ix_access_requests_tenant_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_target_identity_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_role_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_requester_identity_id'), table_name='access_requests')
    op.create_index(op.f('ix_access_requests_identity_id'), 'access_requests', ['identity_id'], unique=False)
    op.drop_column('access_requests', 'extra_data')
    op.drop_column('access_requests', 'requested_valid_until')
    op.drop_column('access_requests', 'requested_valid_from')
    op.drop_column('access_requests', 'reviewed_at')
    op.drop_column('access_requests', 'review_notes')
    op.drop_column('access_requests', 'reviewed_by')
    op.drop_column('access_requests', 'justification')
    op.drop_column('access_requests', 'role_id')
    op.drop_column('access_requests', 'target_identity_id')
    op.drop_column('access_requests', 'requester_identity_id')
    op.drop_column('access_requests', 'tenant_id')
    op.drop_index(op.f('ix_tenant_admins_tenant_id'), table_name='tenant_admins')
    op.drop_index(op.f('ix_tenant_admins_identity_id'), table_name='tenant_admins')
    op.drop_table('tenant_admins')
    op.drop_table('role_entitlements')
    op.drop_index(op.f('ix_platform_admins_identity_id'), table_name='platform_admins')
    op.drop_table('platform_admins')
    op.drop_index(op.f('ix_identity_roles_role_id'), table_name='identity_roles')
    op.drop_index(op.f('ix_identity_roles_identity_id'), table_name='identity_roles')
    op.drop_table('identity_roles')
    op.drop_index(op.f('ix_application_admins_identity_id'), table_name='application_admins')
    op.drop_index(op.f('ix_application_admins_application_id'), table_name='application_admins')
    op.drop_table('application_admins')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_identity_providers_tenant_id'), table_name='identity_providers')
    op.drop_table('identity_providers')
    op.drop_index(op.f('ix_tenants_application_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
